@echo off
REM Praxis Funding Rate Alert � runs every 8h via Task Scheduler
REM Generated by: python scripts/funding_alert.py --setup

cd /d "C:\Data\Development\Python\McTheoryApps\praxis"
"C:\Data\Development\Python\McTheoryApps\praxis\.venv\Scripts\python.exe" "C:\Data\Development\Python\McTheoryApps\praxis\scripts\funding_alert.py" --gate 0.70

REM Keep window open briefly so you can see output
timeout /t 15 /nobreak >nul
